name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: [16-jdk]
    runs-on: ubuntu-20.04
    container:
      image: openjdk:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - run: ./gradlew build test publishToMavenLocal --stacktrace